/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthorRefVO } from './authorRefVO';
import { RefWithLevelVO } from './refWithLevelVO';

export interface LessonDTO { 
    addons: Array<RefWithLevelVO>;
    author?: AuthorRefVO;
    createdAt?: Date;
    extensions: Array<RefWithLevelVO>;
    htmlBody?: string;
    id?: number;
    level: LessonDTO.LevelEnum;
    priority: number;
    replacements: Array<RefWithLevelVO>;
    simplifications: Array<RefWithLevelVO>;
    status: LessonDTO.StatusEnum;
    title?: string;
    updatedAt?: Date;
}
export namespace LessonDTO {
    export type LevelEnum = 'EASY' | 'HARD' | 'MIDDLE';
    export const LevelEnum = {
        EASY: 'EASY' as LevelEnum,
        HARD: 'HARD' as LevelEnum,
        MIDDLE: 'MIDDLE' as LevelEnum
    };
    export type StatusEnum = 'ARCHIVED' | 'PUBLISHED' | 'UNPUBLISHED';
    export const StatusEnum = {
        ARCHIVED: 'ARCHIVED' as StatusEnum,
        PUBLISHED: 'PUBLISHED' as StatusEnum,
        UNPUBLISHED: 'UNPUBLISHED' as StatusEnum
    };
}