/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OptionsDTO { 
    constructions?: Array<string>;
    createdAt: Date;
    id?: number;
    memoryLimit?: string;
    timeLimit?: string;
    updatedAt: Date;
}