/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Easy } from './easy';
import { Hard } from './hard';
import { Middle } from './middle';

export interface ReplacementVO {
    easy?: Easy;
    hard?: Hard;
    learningObjectType: ReplacementVO.LearningObjectTypeEnum;
    middle?: Middle;
}
export namespace ReplacementVO {
    export type LearningObjectTypeEnum = 'LESSON' | 'NONE' | 'TASK' | 'TOPIC';
    export const LearningObjectTypeEnum = {
        LESSON: 'LESSON' as LearningObjectTypeEnum,
        NONE: 'NONE' as LearningObjectTypeEnum,
        TASK: 'TASK' as LearningObjectTypeEnum,
        TOPIC: 'TOPIC' as LearningObjectTypeEnum
    };
}
