/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RoleRequestDTORequestView { 
    messageArgument?: string;
    requiredRole?: RoleRequestDTORequestView.RequiredRoleEnum;
}
export namespace RoleRequestDTORequestView {
    export type RequiredRoleEnum = 'ROLE_ADMIN' | 'ROLE_SUPER_ADMIN' | 'ROLE_TEACHER' | 'ROLE_USER';
    export const RequiredRoleEnum = {
        ADMIN: 'ROLE_ADMIN' as RequiredRoleEnum,
        SUPERADMIN: 'ROLE_SUPER_ADMIN' as RequiredRoleEnum,
        TEACHER: 'ROLE_TEACHER' as RequiredRoleEnum,
        USER: 'ROLE_USER' as RequiredRoleEnum
    };
}