/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaskVO } from './taskVO';
import { UserVO } from './userVO';

export interface TaskResultsVO {
  attempt: number;
  codeReturn?: string;
  completed: boolean;
  id?: string;
  language?: string;
  memory?: string;
  messageOut?: string;
  runtime?: string;
  status?: TaskResultsVO.StatusEnum;
  taskId?: TaskVO;
  userId?: UserVO;
}
export namespace TaskResultsVO {
  export type StatusEnum = 'NOT_CHECKING' | 'RUNNING' | 'COMPLETED';
  export const StatusEnum = {
    NOTCHECKING: 'NOT_CHECKING' as StatusEnum,
    RUNNING: 'RUNNING' as StatusEnum,
    COMPLETED: 'COMPLETED' as StatusEnum,
  };
}
