/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TopicVO } from './topicVO';
import { UserVO } from './userVO';

export interface TaskVO {
  authorId?: UserVO;
  contributors?: Array<UserVO>;
  description?: string;
  id?: string;
  level?: string;
  topicId?: TopicVO;
}
