/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OptionsDTORequestView } from './optionsDTORequestView';
import { TestsDTORequestView } from './testsDTORequestView';

export interface TaskDTORequestView { 
    description?: string;
    level?: TaskDTORequestView.LevelEnum;
    options?: OptionsDTORequestView;
    status?: TaskDTORequestView.StatusEnum;
    tests?: TestsDTORequestView;
    title?: string;
}
export namespace TaskDTORequestView {
    export type LevelEnum = 'EASY' | 'HARD' | 'MIDDLE';
    export const LevelEnum = {
        EASY: 'EASY' as LevelEnum,
        HARD: 'HARD' as LevelEnum,
        MIDDLE: 'MIDDLE' as LevelEnum
    };
    export type StatusEnum = 'ARCHIVED' | 'PUBLISHED' | 'UNPUBLISHED';
    export const StatusEnum = {
        ARCHIVED: 'ARCHIVED' as StatusEnum,
        PUBLISHED: 'PUBLISHED' as StatusEnum,
        UNPUBLISHED: 'UNPUBLISHED' as StatusEnum
    };
}