/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EntityRefRq } from './entityRefRq';

export interface TaskResultsCreateRq {
  taskId?: EntityRefRq;
  userId?: EntityRefRq;
  language?: string;
  sourceCode?: string;
  status?: TaskResultsCreateRq.StatusEnum;
}
export namespace TaskResultsCreateRq {
  export type StatusEnum = 'NOT_CHECKING' | 'RUNNING' | 'COMPLETED';
  export const StatusEnum = {
    NOTCHECKING: 'NOT_CHECKING' as StatusEnum,
    RUNNING: 'RUNNING' as StatusEnum,
    COMPLETED: 'COMPLETED' as StatusEnum,
  };
}
