/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthorRefVO } from './authorRefVO';
import { RefVO } from './refVO';
import { RefWithLevelVO } from './refWithLevelVO';

export interface TopicDTO { 
    addons: Array<RefWithLevelVO>;
    author?: AuthorRefVO;
    createdAt: Date;
    description?: string;
    extensions: Array<RefWithLevelVO>;
    fgosStandards: Array<string>;
    id?: number;
    lessons: Array<RefVO>;
    level: TopicDTO.LevelEnum;
    practicies: Array<RefVO>;
    professionalStandards: Array<string>;
    replacements: Array<RefWithLevelVO>;
    simplifications: Array<RefWithLevelVO>;
    status: TopicDTO.StatusEnum;
    tags: Array<string>;
    title?: string;
    updatedAt: Date;
}
export namespace TopicDTO {
    export type LevelEnum = 'EASY' | 'HARD' | 'MIDDLE';
    export const LevelEnum = {
        EASY: 'EASY' as LevelEnum,
        HARD: 'HARD' as LevelEnum,
        MIDDLE: 'MIDDLE' as LevelEnum
    };
    export type StatusEnum = 'ARCHIVED' | 'PUBLISHED' | 'UNPUBLISHED';
    export const StatusEnum = {
        ARCHIVED: 'ARCHIVED' as StatusEnum,
        PUBLISHED: 'PUBLISHED' as StatusEnum,
        UNPUBLISHED: 'UNPUBLISHED' as StatusEnum
    };
}