/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RefVORequestView } from './refVORequestView';

export interface TopicInteractionDTORequestView { 
    interactionEntity?: RefVORequestView;
    status: TopicInteractionDTORequestView.StatusEnum;
}
export namespace TopicInteractionDTORequestView {
    export type StatusEnum = 'COMPLETED' | 'STARTED';
    export const StatusEnum = {
        COMPLETED: 'COMPLETED' as StatusEnum,
        STARTED: 'STARTED' as StatusEnum
    };
}