/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthorRefVO } from './authorRefVO';
import { RefVO } from './refVO';

export interface TopicDTO {
  addons: Array<RefVO>;
  author?: AuthorRefVO;
  content: Array<RefVO>;
  createdAt: number;
  description?: string;
  extensions: Array<RefVO>;
  fgosStandards: Array<string>;
  id?: number;
  level: TopicDTO.LevelEnum;
  professionalStandards: Array<string>;
  replacements: Array<RefVO>;
  simplifications: Array<RefVO>;
  status: TopicDTO.StatusEnum;
  tags: Array<string>;
  title?: string;
  updatedAt: number;
}
export namespace TopicDTO {
  export type LevelEnum = 'EASY' | 'HARD' | 'MIDDLE';
  export const LevelEnum = {
    EASY: 'EASY' as LevelEnum,
    HARD: 'HARD' as LevelEnum,
    MIDDLE: 'MIDDLE' as LevelEnum,
  };
  export type StatusEnum = 'ARCHIVED' | 'PUBLISHED' | 'UNPUBLISHED';
  export const StatusEnum = {
    ARCHIVED: 'ARCHIVED' as StatusEnum,
    PUBLISHED: 'PUBLISHED' as StatusEnum,
    UNPUBLISHED: 'UNPUBLISHED' as StatusEnum,
  };
}
