/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserDTO {
  createdAt: number;
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  middleName?: string;
  role: UserDTO.RoleEnum;
  updatedAt: number;
}
export namespace UserDTO {
  export type RoleEnum = 'ROLE_ADMIN' | 'ROLE_SUPER_ADMIN' | 'ROLE_TEACHER' | 'ROLE_USER';
  export const RoleEnum = {
    ADMIN: 'ROLE_ADMIN' as RoleEnum,
    SUPERADMIN: 'ROLE_SUPER_ADMIN' as RoleEnum,
    TEACHER: 'ROLE_TEACHER' as RoleEnum,
    USER: 'ROLE_USER' as RoleEnum,
  };
}
