/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent } from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { LessonDTO } from '../model/lessonDTO';
import { LessonDTORequestView } from '../model/lessonDTORequestView';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable()
export class LessonAdminControllerService {
  protected basePath = '//localhost/';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * createLesson
   *
   * @param body lessonDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public createLessonUsingPOST(body: LessonDTORequestView, observe?: 'body', reportProgress?: boolean): Observable<LessonDTO>;
  public createLessonUsingPOST(body: LessonDTORequestView, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LessonDTO>>;
  public createLessonUsingPOST(body: LessonDTORequestView, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LessonDTO>>;
  public createLessonUsingPOST(body: LessonDTORequestView, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling createLessonUsingPOST.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<LessonDTO>('post', `${this.basePath}/admin/lesson`, {
      body: body,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress,
    });
  }

  /**
   * deleteLesson
   *
   * @param id id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteLessonUsingDELETE(id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
  public deleteLessonUsingDELETE(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
  public deleteLessonUsingDELETE(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
  public deleteLessonUsingDELETE(id: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling deleteLessonUsingDELETE.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<any>('delete', `${this.basePath}/admin/lesson/${encodeURIComponent(String(id))}`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress,
    });
  }

  /**
   * linkWithTopic
   *
   * @param id id
   * @param topicId topicId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public linkWithTopicUsingPUT(id: number, topicId: number, observe?: 'body', reportProgress?: boolean): Observable<LessonDTO>;
  public linkWithTopicUsingPUT(id: number, topicId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LessonDTO>>;
  public linkWithTopicUsingPUT(id: number, topicId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LessonDTO>>;
  public linkWithTopicUsingPUT(id: number, topicId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling linkWithTopicUsingPUT.');
    }

    if (topicId === null || topicId === undefined) {
      throw new Error('Required parameter topicId was null or undefined when calling linkWithTopicUsingPUT.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<LessonDTO>(
      'put',
      `${this.basePath}/admin/lesson/${encodeURIComponent(String(id))}/topic/${encodeURIComponent(String(topicId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * makeArchived
   *
   * @param id id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public makeArchivedUsingPOST1(id: number, observe?: 'body', reportProgress?: boolean): Observable<LessonDTO>;
  public makeArchivedUsingPOST1(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LessonDTO>>;
  public makeArchivedUsingPOST1(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LessonDTO>>;
  public makeArchivedUsingPOST1(id: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling makeArchivedUsingPOST1.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<LessonDTO>('post', `${this.basePath}/admin/lesson/${encodeURIComponent(String(id))}/archived`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress,
    });
  }

  /**
   * makePublished
   *
   * @param id id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public makePublishedUsingPOST1(id: number, observe?: 'body', reportProgress?: boolean): Observable<LessonDTO>;
  public makePublishedUsingPOST1(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LessonDTO>>;
  public makePublishedUsingPOST1(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LessonDTO>>;
  public makePublishedUsingPOST1(id: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling makePublishedUsingPOST1.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<LessonDTO>('post', `${this.basePath}/admin/lesson/${encodeURIComponent(String(id))}/published`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress,
    });
  }

  /**
   * makeUnpublished
   *
   * @param id id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public makeUnpublishedUsingPOST1(id: number, observe?: 'body', reportProgress?: boolean): Observable<LessonDTO>;
  public makeUnpublishedUsingPOST1(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LessonDTO>>;
  public makeUnpublishedUsingPOST1(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LessonDTO>>;
  public makeUnpublishedUsingPOST1(id: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling makeUnpublishedUsingPOST1.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<LessonDTO>('post', `${this.basePath}/admin/lesson/${encodeURIComponent(String(id))}/unpublished`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress,
    });
  }

  /**
   * updateLessonAddons
   *
   * @param addonId addonId
   * @param id id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateLessonAddonsUsingPUT(addonId: number, id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
  public updateLessonAddonsUsingPUT(addonId: number, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
  public updateLessonAddonsUsingPUT(addonId: number, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
  public updateLessonAddonsUsingPUT(addonId: number, id: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (addonId === null || addonId === undefined) {
      throw new Error('Required parameter addonId was null or undefined when calling updateLessonAddonsUsingPUT.');
    }

    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling updateLessonAddonsUsingPUT.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<any>('put', `${this.basePath}/admin/lesson/${encodeURIComponent(String(id))}/addon/${encodeURIComponent(String(addonId))}`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress,
    });
  }

  /**
   * updateLessonExtensions
   *
   * @param extensionId extensionId
   * @param id id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateLessonExtensionsUsingPUT(extensionId: number, id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
  public updateLessonExtensionsUsingPUT(extensionId: number, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
  public updateLessonExtensionsUsingPUT(extensionId: number, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
  public updateLessonExtensionsUsingPUT(extensionId: number, id: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (extensionId === null || extensionId === undefined) {
      throw new Error('Required parameter extensionId was null or undefined when calling updateLessonExtensionsUsingPUT.');
    }

    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling updateLessonExtensionsUsingPUT.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<any>(
      'put',
      `${this.basePath}/admin/lesson/${encodeURIComponent(String(id))}/extension/${encodeURIComponent(String(extensionId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * updateLessonReplacements
   *
   * @param id id
   * @param replacementId replacementId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateLessonReplacementsUsingPUT(id: number, replacementId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
  public updateLessonReplacementsUsingPUT(id: number, replacementId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
  public updateLessonReplacementsUsingPUT(id: number, replacementId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
  public updateLessonReplacementsUsingPUT(id: number, replacementId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling updateLessonReplacementsUsingPUT.');
    }

    if (replacementId === null || replacementId === undefined) {
      throw new Error('Required parameter replacementId was null or undefined when calling updateLessonReplacementsUsingPUT.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<any>(
      'put',
      `${this.basePath}/admin/lesson/${encodeURIComponent(String(id))}/replacement/${encodeURIComponent(String(replacementId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * updateLessonSimplifications
   *
   * @param id id
   * @param simplificationId simplificationId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateLessonSimplificationsUsingPUT(id: number, simplificationId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
  public updateLessonSimplificationsUsingPUT(
    id: number,
    simplificationId: number,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<any>>;
  public updateLessonSimplificationsUsingPUT(id: number, simplificationId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
  public updateLessonSimplificationsUsingPUT(id: number, simplificationId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling updateLessonSimplificationsUsingPUT.');
    }

    if (simplificationId === null || simplificationId === undefined) {
      throw new Error('Required parameter simplificationId was null or undefined when calling updateLessonSimplificationsUsingPUT.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<any>(
      'put',
      `${this.basePath}/admin/lesson/${encodeURIComponent(String(id))}/simplification/${encodeURIComponent(String(simplificationId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * updateLesson
   *
   * @param body lessonDTO
   * @param id id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateLessonUsingPUT(body: LessonDTORequestView, id: number, observe?: 'body', reportProgress?: boolean): Observable<LessonDTO>;
  public updateLessonUsingPUT(body: LessonDTORequestView, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LessonDTO>>;
  public updateLessonUsingPUT(body: LessonDTORequestView, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LessonDTO>>;
  public updateLessonUsingPUT(body: LessonDTORequestView, id: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling updateLessonUsingPUT.');
    }

    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling updateLessonUsingPUT.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<LessonDTO>('put', `${this.basePath}/admin/lesson/${encodeURIComponent(String(id))}`, {
      body: body,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress,
    });
  }
}
